language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pyradd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pyradd/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  evn: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-404571580199"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  